### ISSUE TITLE
Dynamic serializer fields are not supported

### ISSUE THREAD

**Issue by melvinkcx** [django-commons/drf-excel#108]
Hi, I'm trying to use a serializer that adds fields dynamically. However, XLSXRenderer is not able to pick up those fields. 

Here's a simple example:

```python
class MySerializer(serializers.Serializer):
    field_1 = serializers.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["dynamic_field_1"] = serializers.CharField(label="Dynamic Field", allow_null=True)
```

In the output XLSX, only `field_1` is included.

I believe the use of `serializer.get_fields()` is the root cause:

https://github.com/django-commons/drf-excel/blob/0d47d7bdfcfbe8d09e6186bfea46f8cdc76e2adc/drf_excel/renderers.py#L277

The default implementation of `get_fields()` in BaseSerializer returns `self._declared_fields`.  This can be resolved by referencing to `serializer.fields` instead. 

Let me know what you think. I can create an MR to fix it. 

IMO, I think we should update this line to use `serializer.fields` as well.

https://github.com/django-commons/drf-excel/blob/0d47d7bdfcfbe8d09e6186bfea46f8cdc76e2adc/drf_excel/renderers.py#L156C18-L156C29

**Comment by browniebroke** [comment]
Interesting... Didn't know it was a thing, is it something well supported by DRF? I'm wondering if there would be any unintended side effects. If you can make a PR with some good testing, I'll be happy to look into it, yes.

**Comment by FlipperPA** [comment]
There's another reference to `get_fields()` here: https://github.com/django-commons/drf-excel/blob/0d47d7bdfcfbe8d09e6186bfea46f8cdc76e2adc/drf_excel/renderers.py#L244

We should review and make sure there wouldn't be side-effects there.

**Comment by rptmat57** [comment]
I thought `serializer.fields` was already calling `get_fields()` anyway... but I might be wrong, I haven't looked at that code in a bit.

**Comment by melvinkcx** [comment]
@rptmat57 you're right. `serializer.fields` is calling `get_fields()`. However, if extra fields are being added dynamically to `serializer.fields` in the constructor, `get_fields()` of the `BaseSerializer` will not be able to include them. Hence, I think it'd be better to retrieve all fields with `serializer.fields` rather than `serializer.get_fields()`
