### ISSUE TITLE
Transfer Project to Django Commons

### ISSUE THREAD

**Issue by FlipperPA** [django-commons/drf-excel#86]
At DjangoCon US, we're moving this project to Django Commons for additional support and continuity planning.

@rptmat57 — can you join Django Commons here, and we'll keep you as a maintainer? I'm fairly certain @willtho89 has moved on, but Thomas, if you'd like to stay involved we'd love to have you too.

**Comment by browniebroke** [comment]
Thanks for the nudge, forgot about it!
